name: API Test Automation with TypeScript, Jest, and Supertest

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 20 * * 6
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '20'
    - name: Install Packages
      run: |
       npm install
    - name: Run Tests
      run: |
       npm test
    - name: Output the run Details
      uses: actions/upload-artifact@v4
      with: 
       name: RunReports
       path: html-report

